-- =============================================================================
-- REALISTIC SAMPLE TICKETS FOR ECHOLAB A/B TESTING PLATFORM
-- =============================================================================
-- These tickets represent real issues users face with experimentation platforms
-- They're designed to cluster into meaningful pain points
-- =============================================================================

-- CLUSTER 1: Experiment Setup Complexity (15 tickets)
-- Pain Point: Users struggle with complex experiment configuration

INSERT INTO raw.tickets (ticket_key, title, description, priority, status, reporter, product, component, created_at, updated_at) VALUES
('ECHO-001', 'Too many steps to create an experiment', 'Creating a new A/B test requires clicking through 5 different screens. Each screen has confusing terminology like "allocation split" and "traffic distribution". Can we simplify this to a single page with better labels?', 'High', 'Open', 'sarah.chen', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('ECHO-002', 'Cannot copy experiment configuration', 'I run similar experiments every week and have to manually re-enter all the same settings (variants, metrics, audience). Need a "duplicate experiment" button to copy everything from a previous test.', 'Medium', 'Open', 'mike.patel', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
('ECHO-003', 'Unclear variant naming requirements', 'System rejected my experiment because variant names were invalid. Error message just said "invalid format" with no explanation. What characters are allowed? What is the max length? Need better error messages.', 'Low', 'Open', 'jen.kim', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
('ECHO-004', 'No validation before launching experiment', 'Launched experiment with wrong metric configuration. System should validate everything before going live - check metrics exist, variants are properly configured, audience size is sufficient, etc.', 'High', 'Open', 'alex.torres', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 days'),
('ECHO-005', 'Experiment templates missing', 'Would love pre-built templates for common experiment types (pricing tests, button color tests, checkout flow tests). Starting from scratch every time is tedious.', 'Medium', 'Open', 'priya.sharma', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
('ECHO-006', 'Cannot edit running experiments', 'Discovered typo in variant description after launching. Cannot edit anything while experiment is running. At minimum should allow editing descriptions and labels that don''t affect the test itself.', 'Medium', 'In Progress', 'david.wong', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day'),
('ECHO-007', 'Traffic allocation UI is confusing', 'The slider for traffic allocation snaps to weird percentages. Wanted 33/33/33 for 3-way test but it keeps jumping to 32/34/34. Need better control or at least type exact percentages.', 'Low', 'Open', 'emma.johnson', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('ECHO-008', 'Missing experiment start date scheduling', 'Have to manually start experiments at specific times (e.g., Monday 9am for email launch). Need ability to schedule experiment start in advance rather than clicking "Start" at exact moment.', 'Medium', 'Open', 'raj.kumar', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('ECHO-009', 'No bulk experiment creation', 'Running 20 similar experiments for different user segments. Have to create each one individually which takes hours. Need bulk creation from CSV or API.', 'High', 'Open', 'lisa.anderson', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
('ECHO-010', 'Variant preview not working', 'The "Preview" button shows same content for all variants. Cannot visually verify variants before launching. This is critical for frontend tests.', 'High', 'Open', 'tom.garcia', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '4 days', NOW() - INTERVAL '3 days'),
('ECHO-011', 'Experiment naming validation too strict', 'Cannot use spaces or special characters in experiment names. Error appears after filling entire form. Validate experiment name on first field to save time.', 'Low', 'Open', 'nina.scott', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
('ECHO-012', 'Missing experiment description field', 'No place to add detailed notes about experiment hypothesis, expected impact, or why we''re running it. Team members don''t understand context when reviewing experiments.', 'Medium', 'Open', 'chris.lee', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
('ECHO-013', 'Cannot set minimum sample size', 'Experiments auto-complete based on time but ignore sample size. Need option to set minimum users per variant before allowing completion.', 'Medium', 'Open', 'amanda.brown', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
('ECHO-014', 'Audience targeting too basic', 'Can only target by country and device. Need more advanced segmentation - user signup date, subscription tier, previous purchase behavior, etc.', 'High', 'Open', 'kevin.park', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('ECHO-015', 'No experiment draft auto-save', 'Browser crashed while setting up complex experiment. Lost all my work. Please auto-save drafts every 30 seconds.', 'Medium', 'Open', 'sophie.martin', 'Experimentation', 'Experiment Setup', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days');

-- CLUSTER 2: Analytics & Reporting Issues (12 tickets)
-- Pain Point: Poor data visualization and unclear statistical results

INSERT INTO raw.tickets (ticket_key, title, description, priority, status, reporter, product, component, created_at, updated_at) VALUES
('ECHO-016', 'Dashboard loads very slowly', 'Analytics dashboard takes 45-60 seconds to load with 10+ running experiments. Charts render one at a time creating jarring experience. Need better performance or at least loading skeleton.', 'High', 'Open', 'robert.wilson', 'Analytics', 'Dashboard', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
('ECHO-017', 'Cannot export experiment results', 'Need to include results in weekly report but no export button. Have to manually screenshot and copy-paste numbers into slides. Need CSV/Excel export with all metrics.', 'Medium', 'Open', 'maria.lopez', 'Analytics', 'Reporting', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('ECHO-018', 'Statistical significance not explained', 'Dashboard shows "95% confidence" but team members don''t understand what this means. Need tooltip or help text explaining statistical significance in plain language.', 'Low', 'Open', 'brian.taylor', 'Analytics', 'Statistics', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
('ECHO-019', 'Charts not updating in real-time', 'Have to manually refresh page to see updated metrics. Competitor tools show real-time updates. Expected automatic refresh at least every 5 minutes.', 'Medium', 'In Progress', 'jessica.white', 'Analytics', 'Dashboard', NOW() - INTERVAL '4 days', NOW() - INTERVAL '2 days'),
('ECHO-020', 'Missing conversion funnel visualization', 'Can see overall conversion rate but cannot see where in the funnel variants differ. Need step-by-step funnel chart to identify exact drop-off points.', 'High', 'Open', 'daniel.harris', 'Analytics', 'Visualization', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
('ECHO-021', 'Cannot compare multiple experiments', 'Running 3 pricing experiments simultaneously. Want to see all results side-by-side but can only view one experiment at a time. Need multi-experiment comparison view.', 'Medium', 'Open', 'rachel.green', 'Analytics', 'Dashboard', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('ECHO-022', 'Time series data missing', 'Results show final numbers but no daily/hourly trends. Cannot see if winning variant was consistent over time or just spiked at end. Need time series charts.', 'High', 'Open', 'james.miller', 'Analytics', 'Visualization', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('ECHO-023', 'Mobile analytics viewport broken', 'Viewing results on mobile shows cut-off charts and unreadable tables. Need responsive design for mobile analytics access.', 'Low', 'Open', 'linda.davis', 'Analytics', 'Mobile', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
('ECHO-024', 'No segment breakdowns', 'Want to see experiment results broken down by user segment (new vs returning, mobile vs desktop, etc). Currently only see aggregate numbers.', 'High', 'Open', 'paul.anderson', 'Analytics', 'Segmentation', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
('ECHO-025', 'P-value not shown', 'Dashboard shows "statistically significant" but doesn''t show actual p-value. Our data science team needs this for documentation and validation.', 'Low', 'Open', 'karen.thompson', 'Analytics', 'Statistics', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
('ECHO-026', 'Cannot set custom date ranges', 'Analytics locked to "last 7 days" or "last 30 days". Need custom date range picker to analyze specific time periods or exclude weekends.', 'Medium', 'Open', 'steven.moore', 'Analytics', 'Dashboard', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
('ECHO-027', 'Metrics dashboard missing key numbers', 'Want to see sample size, MDE (minimum detectable effect), and test duration at top of dashboard. Currently buried in settings or not shown at all.', 'Medium', 'Open', 'ashley.jackson', 'Analytics', 'Dashboard', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days');

-- CLUSTER 3: Integration Problems (10 tickets)
-- Pain Point: Difficult integrations with analytics tools and data pipelines

INSERT INTO raw.tickets (ticket_key, title, description, priority, status, reporter, product, component, created_at, updated_at) VALUES
('ECHO-028', 'Segment integration not sending events', 'Connected Segment but experiment exposure events not appearing in our data warehouse. Documentation unclear on which events are sent and what properties they include.', 'High', 'Open', 'michael.nguyen', 'Integrations', 'Segment', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
('ECHO-029', 'Google Analytics 4 integration missing', 'Only supports Universal Analytics which is deprecated. Need GA4 integration to send experiment data to Google Analytics 4.', 'High', 'Open', 'sarah.rodriguez', 'Integrations', 'Google Analytics', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('ECHO-030', 'Slack notifications unreliable', 'Sometimes get Slack notification when experiment completes, sometimes don''t. Very inconsistent. Need reliable notifications for experiment lifecycle events.', 'Medium', 'In Progress', 'john.phillips', 'Integrations', 'Slack', NOW() - INTERVAL '4 days', NOW() - INTERVAL '2 days'),
('ECHO-031', 'Webhook events undocumented', 'Set up webhooks but payload format not documented. What fields are included? What triggers each event? Need API documentation for webhooks.', 'Medium', 'Open', 'emily.campbell', 'Integrations', 'Webhooks', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
('ECHO-032', 'Cannot filter Mixpanel events', 'Sending all experiment events to Mixpanel creating huge volume. Need ability to filter which events/experiments get sent to reduce costs.', 'Low', 'Open', 'andrew.turner', 'Integrations', 'Mixpanel', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('ECHO-033', 'Data warehouse export delays', 'BigQuery export runs once daily at 3am. Need more frequent exports (hourly) or real-time streaming to warehouse for timely analysis.', 'Medium', 'Open', 'michelle.carter', 'Integrations', 'BigQuery', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
('ECHO-034', 'Amplitude integration setup complex', 'Took 3 hours to configure Amplitude integration with multiple support tickets. Process should be simple OAuth flow like Segment.', 'Medium', 'Open', 'ryan.scott', 'Integrations', 'Amplitude', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
('ECHO-035', 'API rate limiting too strict', 'Hitting API rate limit (100 req/min) when pulling data for internal dashboard. Need higher limits for enterprise customers or ability to request increase.', 'High', 'Open', 'laura.evans', 'Integrations', 'API', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
('ECHO-036', 'Missing Snowflake connector', 'Our data warehouse is Snowflake but only BigQuery and Redshift supported. Need native Snowflake integration to export experiment results.', 'Medium', 'Open', 'jason.martinez', 'Integrations', 'Data Warehouse', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
('ECHO-037', 'SDK events not batching', 'JavaScript SDK sends event for every page view individually. This creates performance issues and high bandwidth usage. Need event batching with configurable flush intervals.', 'Low', 'Open', 'olivia.baker', 'Integrations', 'SDK', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days');

-- CLUSTER 4: Performance & Reliability (8 tickets)
-- Pain Point: System performance issues and reliability concerns

INSERT INTO raw.tickets (ticket_key, title, description, priority, status, reporter, product, component, created_at, updated_at) VALUES
('ECHO-038', 'Feature flag evaluation slow', 'Page load increased by 200ms after adding feature flags. Evaluation should be near-instant (<10ms) or cached locally.', 'High', 'Open', 'william.thomas', 'Performance', 'Feature Flags', NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days'),
('ECHO-039', 'Dashboard timeouts with large datasets', 'Experiments with 1M+ users cause dashboard to timeout. Query optimization needed or implement pagination/sampling for large experiments.', 'High', 'In Progress', 'sophia.hill', 'Performance', 'Database', NOW() - INTERVAL '3 days', NOW() - INTERVAL '1 day'),
('ECHO-040', 'SDK bundle size too large', 'JavaScript SDK is 150KB gzipped. This impacts page speed significantly. Competitors have 20-30KB SDKs. Need tree-shaking and code splitting.', 'Medium', 'Open', 'nathan.adams', 'Performance', 'SDK', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
('ECHO-041', 'Experiment assignment inconsistent', 'Users reporting different variants on page refresh. Sticky bucketing not working correctly. Critical issue affecting experiment validity.', 'Critical', 'Open', 'grace.mitchell', 'Reliability', 'Assignment', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),
('ECHO-042', 'API downtime during deployments', 'API goes offline for 5-10 minutes during deployments every Tuesday. Need zero-downtime deployments or at least advanced warning.', 'High', 'Open', 'ethan.roberts', 'Reliability', 'Infrastructure', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
('ECHO-043', 'Memory leak in real-time updates', 'Dashboard left open overnight consumed 4GB RAM and crashed browser. Memory leak in WebSocket connection for real-time updates.', 'Medium', 'Open', 'isabella.wood', 'Performance', 'Memory', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('ECHO-044', 'Batch processing delays', 'Nightly batch job that calculates statistics sometimes takes 6+ hours. Need to investigate query performance and add incremental processing.', 'Medium', 'Open', 'lucas.garcia', 'Performance', 'Batch Processing', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
('ECHO-045', 'CDN cache causing stale data', 'Users seeing outdated experiment variants due to aggressive CDN caching. Need proper cache invalidation strategy or shorter TTLs for experiment configs.', 'High', 'Open', 'mia.rodriguez', 'Reliability', 'CDN', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days');

-- CLUSTER 5: User Experience Issues (7 tickets)
-- Pain Point: Confusing UI/UX and missing features

INSERT INTO raw.tickets (ticket_key, title, description, priority, status, reporter, product, component, created_at, updated_at) VALUES
('ECHO-046', 'No onboarding tutorial', 'New team members struggle to understand platform. Need interactive tutorial or guided tour showing how to create first experiment.', 'Low', 'Open', 'aiden.martinez', 'UX', 'Onboarding', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
('ECHO-047', 'Search functionality missing', 'Have 100+ experiments and cannot search by name or filter by status. Need robust search with filters for status, date range, owner, etc.', 'High', 'Open', 'chloe.anderson', 'UX', 'Navigation', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
('ECHO-048', 'Dark mode support', 'Working late nights and bright white UI is harsh on eyes. Please add dark mode theme option in user settings.', 'Low', 'Open', 'noah.taylor', 'UX', 'Theming', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
('ECHO-049', 'Bulk actions on experiments', 'Want to archive or pause multiple experiments at once. Currently have to click each one individually which is time-consuming.', 'Medium', 'Open', 'ava.thomas', 'UX', 'Bulk Operations', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('ECHO-050', 'Mobile app missing', 'Need to check experiment results on phone but mobile web is clunky. Competitors have native iOS/Android apps for monitoring on-the-go.', 'Low', 'Open', 'liam.jackson', 'UX', 'Mobile', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
('ECHO-051', 'Experiment history not preserved', 'When experiment ends, all historical data seems to disappear. Need archive of past experiments with full results for future reference.', 'High', 'Open', 'emma.white', 'UX', 'Data Retention', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
('ECHO-052', 'Keyboard shortcuts missing', 'Power users want keyboard shortcuts for common actions (create experiment: Cmd+N, navigate experiments: J/K keys, etc).', 'Low', 'Open', 'oliver.harris', 'UX', 'Accessibility', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days');

SELECT COUNT(*) as total_tickets_inserted FROM raw.tickets;
